package com.example.domain.model

/**
 * Structured AI analysis result for a single trend.
 *
 * Every field has a safe default so the UI never crashes on missing data.
 * Generated by Gemini from real news signals — not hardcoded.
 */
data class TrendAnalysisResult(
    val trendId: String = "",
    val trendSummary: String = "",
    val whyTrending: String = "",
    val sentiment: String = "Neutral",
    val sentimentScore: Int = 50,
    val growthPrediction: String = "Stable",
    val predictedGrowth: Int = 0,
    val viralProbability: Int = 0,
    val aiConfidence: Int = 0,
    val relatedTopics: List<String> = emptyList(),
    val keyInsights: List<String> = emptyList(),
    val riskFactors: List<String> = emptyList(),
    val analyzedAt: Long = System.currentTimeMillis()
) {
    /** Returns true if this analysis was generated within the last [ttlMillis]. */
    fun isRecent(ttlMillis: Long = 30 * 60 * 1000): Boolean =
        System.currentTimeMillis() - analyzedAt < ttlMillis

    companion object {
        /** Default empty / no-data result used when no cached analysis exists. */
        val EMPTY = TrendAnalysisResult()

        /** Friendly fallback when the API key is not configured. */
        val NOT_CONFIGURED = TrendAnalysisResult(
            trendSummary = "AI analysis requires a Gemini API key.",
            whyTrending = "Configure your Gemini API key in local.properties to enable AI-powered trend analysis.",
            sentiment = "Unknown",
            sentimentScore = 0,
            growthPrediction = "Unknown",
            predictedGrowth = 0,
            viralProbability = 0,
            aiConfidence = 0,
            relatedTopics = emptyList(),
            keyInsights = listOf("Add GEMINI_API_KEY to local.properties"),
            riskFactors = listOf("API key not configured")
        )

        /** Offline fallback with a helpful message. */
        val OFFLINE = TrendAnalysisResult(
            trendSummary = "No cached AI analysis available.",
            whyTrending = "Connect to the internet to generate AI insights for this trend.",
            sentiment = "Unknown",
            keyInsights = listOf("Connect to the internet to generate AI insights"),
            riskFactors = listOf("Device is offline")
        )
    }
}
